' Register System
@startuml
|Customer/Guide/Fortune Teller|
start
:register;
:send info to server;
|Server|
:save info;
if (Type of User) is (Customer) then
	:Send confirm mail to Customer;
else (Guide/Fortune Teller)
	|Server|
	:Send approve to admin;
	|Admin|
	:Check info;
	if (Correct info) is (Correct) then
		:Send confirm mail to Guide/Fortune Teller;
	else (Incorrect)
		:Send reject mail to Guide/Fortune Teller;
	endif
endif
|User/Guide/Fortune Teller|
:Confirm Register;
:Login;
stop

@enduml

' Login System

@startuml
|User|
start
:Login;
:Send mail and password info to server;
|Server|
:Check info;
if (isCorrect) is (Correct) then
	:Generate limited time token;
	:Save token to Database;
	:Send Page and token to User;
else (inCorrect)
	:Send Error page to User;
endif

|User|
:Get respone from server;
if (Access) is (true) then
	:Save token to cookie;
	:Redirect to Home page;
	if (User) is (Customer) then
	:Show Customer page;
	:Selected Service;
	:Redirect to Service page;
	else (Guide/Fortune Teller)
	:Show Guide/Fortune Teller page;
	endif
else (false)
	:Show Error Dialog;
	:Redirect to Login page;
endif
stop
@enduml

' Customer select Service System

@startuml
|Customer|
start
:Login;
:Select Service;
:Send request to server;
|Server|
:Check token;
:Check request Service;
:Return Service page;
|Customer|
:Show Service page;
:Select Guide/Fortune Teller;
:Check the avaliable date;
|Server|
:Send the avaliable date to Customer;
|Customer|
:Select date;
:Send request to server;
|Server|
:Check token;
:Check request date;
if (isAvaliable) is (false) then
	:Send Error page to Customer;
	|Customer|
	:Show Error page;
else (true)
	|Server|
	:Redirect to Payment page;
endif
stop
@enduml

' Payment System

@startuml
|Customer|
start
:Select Payment method;
|Server|
if (Paymeny method) is (QRCode) then
	|Server|
	:Generate QRCode;
	:Send QRCode to Customer;
	|Customer|
	:Show QRCode;
	:Scan QRCode;
	:Send slip to server;
else (Credit Card)
	|Server|
	:Redirect to Credit Card page;
	:Send request to Bank;
	|Bank|
	:Check request;
	:Generate transaction;
	|Customer|
	:Fill Credit Card info;
	:Send Credit Card info to Bank;
	|Bank|
	:Check Credit Card info;
	:Send transaction result to Server;
	|Server|
	:Check transaction result;
	:Save transaction result;
	:Update payment status on DB;
endif
stop
@enduml

' Guide/Fortune Teller add Service System

@startuml
|Guide/Fortune Teller|
start
:Login;
:Select menu;
:Send request to server;
|Server|
:Check request;
if (Request Page) is (Add Service) then
	:Return Add service page to Guide/Fortune Teller;
else (Add working time)
	:Return Add working time page to Guide/Fortune Teller;
endif
|Guide/Fortune Teller|
:Show page;
:Fill info;
if (Page) is (Add working time) then
	:Send request to server;
	|Server|
	:Check token;
	:Return Add working time page;
	|Guide/Fortune Teller|
	:Show page;
	:Add time;
	:Save time to server;
else (Add Service)
	:Send request to server;
	|Server|
	:Check token;
	:Send approve to admin;
	|Admin|
	:Check info;
	if (Correct info) is (Correct) then
		:Save info to DB;
	else (Incorrect)
	endif
|Server|
:Send confirm mail to Guide/Fortune Teller;
endif
|Guide/Fortune Teller|
stop
@enduml

' Send prove of services System

@startuml
|Guide/Fortune Teller|
start
:Press finish job;
:Send the prove of the job;
repeat
:Send prove to server;
|Server|
:Save prove to DB;
:Send prove to admin;
|Admin|
:Check prove;
:send result to server;
|Server|
:Check result;
if (Result) is (Incorrect) then
	:Send reject mail to Guide/Fortune Teller;
	|Guide/Fortune Teller|
	:Resend prove;
else (Correct)
	|Server|
	:Update status to DB;
endif
|Guide/Fortune Teller|
repeat while (reject prove) is (Yes) not (No)
stop
@enduml

' Feedback System

@startuml
|Customer|
start
:Login;
:Select finish service;
repeat
:Send feedback to server;
|Server|
:Save feedback to DB;
:Send feedback to approve with admin;
|Admin|
:Check feedback;
:Send result to server;
|Server|
:Check result;
if (Result) is (Incorrect) then
	:Send reject mail to Customer;
else (Correct)
	|Server|
	:Update status to DB;
endif
|Customer|
repeat while (reject feedback) is (Yes) not (No)
stop
@enduml