' Register System
@startuml
|Customer/Guide/Fortune Teller|
start
:register;
:send info to server;
|Server|
:save info;
if (Type of User) is (Customer) then
	:Send confirm mail to Customer;
else (Guide/Fortune Teller)
	|Server|
	:Send approve to admin;
	|Admin|
	:Check info;
	if (Correct info) is (Correct) then
		:Send confirm mail to Guide/Fortune Teller;
	else (Incorrect)
		:Send reject mail to Guide/Fortune Teller;
	endif
endif
|Customer/Guide/Fortune Teller|
:Confirm Register;
:Login;
stop

@enduml

' Login System

@startuml
|User|
start
:Login;
|System|
:Check info;
if (isCorrect) is (correct) then
	:Send Home Page to User;
else (inCorrect)
	:Send Error page to User;
endif

|User|
:Access to Website;
stop
@enduml

' Customer select Service System

@startuml
|Customer|
start
:Login;
:Select Service;
|Server|
:Return Service page;
|Customer|
:Show Service page;
:Select Guide/Fortune Teller;
:Check the avaliable date;
|Server|
:Send the avaliable date to Customer;
|Customer|
:Select date;
|Server|
:Check avaliable date;
if (isAvaliable) is (false) then
	:Send Error page to Customer;
	|Customer|
	:Show Error page;
else (true)
	|Server|
	:Redirect to Payment page;
endif
stop
@enduml

' Payment System

@startuml
|Customer|
start
:Select Payment method;
|Server|
if (Paymeny method) is (QRCode) then
	|Server|
	:Send QRCode to Customer;
	|Customer|
	:Show QRCode;
	:Scan QRCode;
	:Send slip to server;
else (Credit Card)
	|Server|
	:Redirect to Credit Card page;
	|Bank|
	:Generate transaction;
	|Customer|
	:Fill Credit Card info;
	:Send Credit Card info to Bank;
	|Bank|
	:Check Credit Card info;
	:Send transaction result to Server;
	|Server|
	:Check transaction result;
endif
stop
@enduml

' Guide/Fortune Teller add Service System

@startuml
|Guide/Fortune Teller|
start
:Login;
:Select menu;
|Server|
if (select Page) is (Add Service) then
	:Return Add service page to Guide/Fortune Teller;
else (Add working time)
	:Return Add working time page to Guide/Fortune Teller;
endif
|Guide/Fortune Teller|
if (Page) is (Add working time) then
	:Select menu;
	:Click Add working time;
	|Server|
	:Return Add working time page;
	|Guide/Fortune Teller|
	:Add time;
else (Add Service)
	:Send service to server;
	|Server|
	:Send approve to admin;
	|Admin|
	:Check info;
	if (Correct info) is (Correct) then
		:Send confirm mail to Guide/Fortune Teller;
	else (Incorrect)
	endif
endif
|Guide/Fortune Teller|
stop
@enduml

' Send prove of services System

@startuml
|Guide/Fortune Teller|
start
:Press finish job;
:Send the prove of the job;
repeat
:Send prove to server;
|Server|
:Send prove to admin;
|Admin|
:Check prove;
:send result;
|Server|
:Check result;
if (Result) is (Incorrect) then
	:Send reject mail to Guide/Fortune Teller;
	|Guide/Fortune Teller|
	:Resend prove;
else (Correct)
	|Server|
	:Send confirm mail to Guide/Fortune Teller;
endif
|Guide/Fortune Teller|
repeat while (reject prove) is (Yes) not (No)
stop
@enduml

' Feedback System

@startuml
|Customer|
start
:Select finish service;
repeat
:Send feedback to server;
|Server|
:Send feedback to approve with admin;
|Admin|
:Check feedback;
:Send result;
|Server|
:Check result;
if (Result) is (Incorrect) then
	:Send reject mail to Customer;
else (Correct)
	|Server|
	:Send confirm mail to Customer;
endif
|Customer|
repeat while (reject feedback) is (Yes) not (No)
stop
@enduml