' Register a new user
@startuml
actor User
actor Admin
participant "Frontend" as FE
participant "Backend" as BE
User -> FE: Fill info
activate FE
FE -> BE: Post info
deactivate FE
note over FE: POST /api/register
activate BE
BE -> BE: Validate input
BE -> BE: Save info
deactivate BE
group Request Approve account
	note over BE: If user is Guide/Fortune Teller
	BE -->> Admin: Request Approve account
	activate BE
	activate Admin
	Admin -> BE: Approve account
	deactivate BE
	deactivate Admin
end
group Send confirmation mail
	note over BE : If user is Customer
	BE -->> User: Mail to confirm account
	activate User
	User -> BE: Confirm account
end
BE -> User: Return user type
hide footbox
@enduml

' Login

@startuml
actor User
participant "Frontend" as FE
participant "Backend" as BE
note over FE: POST /api/login
User -> FE: Fill login info
activate FE
FE -> BE: Post login
activate BE
BE -> BE: Save token
BE -> BE: Validate input
BE -->> FE: Return token
deactivate BE
FE -> FE: Redirect to home
FE -->> User: Return home page
hide footbox
@enduml


' Customer book service

@startuml
actor Customer
actor "Guide/Fortune Teller" as GF
participant "Frontend" as FE
participant "Backend" as BE
Customer -> FE: Access to menu page
activate FE
note over FE: GET /api/menu
FE -> BE: Request Get type of services
activate BE
BE -> BE: Get type of services
BE -->> FE: Return type of services
deactivate BE
FE -->> Customer: Display type of services
deactivate FE
Customer -> FE: Select service type
activate FE
FE -> BE: Request Get service List
activate BE
BE -> BE: Get service List
BE -->> FE: Return service List
deactivate BE
FE -->> Customer: Display Avaliable service List
deactivate FE
Customer -> FE: book service
activate FE
FE -> BE: Request POST selected service
activate BE
BE -> BE: Save selected service
BE -->> FE: Return select schedule page
deactivate BE
deactivate FE
Customer -> FE: book schedule
activate FE
FE -> BE: POST selected schedule
deactivate FE
activate BE
BE -> BE: Save selected schedule
BE -> GF: Send book confirmation mail
activate GF
GF -> BE: Confirm book schedule
deactivate GF
BE -> BE: Update status of selected schedule
group Unavailable schedule
	note over BE: If schedule is unavailable
	BE -->> Customer: Return Select schedule page
end
group Available schedule
	note over BE: If schedule is available
	BE -->> Customer: Return confirm mail
end
deactivate BE
hide footbox
@enduml

' Guide and Fortune teller add service and schedule

@startuml
actor "Guide/Fortune Teller" as GF
actor Admin
participant "Frontend" as FE
participant "Backend" as BE
GF -> FE: Fill service info
activate FE
FE -> FE: Check payload service info
FE -> BE: Request POST service
activate BE
BE -> BE: Save service
BE -->> Admin: Request Approve service
activate Admin
Admin -> BE: Approve service
BE -> BE: Update status of service
deactivate Admin
BE -->> GF: GET add service status
hide footbox
@enduml

' Payment process

@startuml
actor Customer
participant "Frontend" as FE
participant "Backend" as BE
participant "Bank" as Bank
FE -> BE: Get payment method page
activate FE
activate BE
BE -> BE: Get payment method
BE -->> FE: Return payment method
deactivate BE
deactivate FE
Customer -> FE: Select payment method
activate FE
group Select Credit Card
	FE -> BE: GET credit card form
	FE -> FE: Return credit card page
	Customer -> FE: Fill credit card info
	FE -> FE: Check payload credit card info
	FE -> BE: POST ordered service
	activate BE
	BE -> BE: Save ordered service
	BE -> Bank: Request payment
	activate Bank
	Bank -> Bank: Validate payment
	Bank -->> BE: Return payment transaction
	deactivate Bank
	BE -> BE: Save transaction
	BE -> BE: Update status of payment
	BE -->> FE: Return payment transaction
	deactivate BE
end
group Select QR code method
	Customer -> FE: Select QR code method
	FE -> BE: POST request QR code
	activate BE
	BE -> BE: Save ordered service
	BE -> BE: Generate QR code
	BE -> BE: Update status of payment
	BE -->> FE: Return QR code
	deactivate BE
	Customer -> FE: Scan QR code
	FE -> BE: POST ordered service
	activate BE
	BE -> BE: Validate Payment
	BE -> BE: Update status of payment
	BE -->> FE: Return payment transaction
	deactivate BE
end
hide footbox
@enduml

' Guide and Fortune teller send report

@startuml
actor "Guide/Fortune Teller" as GF
actor Admin
participant "Frontend" as FE
participant "Backend" as BE
GF -> FE: Fill report info
activate FE
FE -> BE: Request POST report
deactivate FE
activate BE
BE -> BE: Save report
BE -->> Admin: Request Approve report
activate Admin
Admin -> BE: Approve report
deactivate Admin
BE -> BE: Update status of report
BE -->> FE: Return confirmation
BE -->> GF: Return confirmation mail
deactivate FE
deactivate BE
hide footbox
@enduml

' Customer give feedback

@startuml
actor Customer
actor Admin
actor "Guide/Fortune Teller" as GF
participant "Frontend" as FE
participant "Backend" as BE
Customer -> FE: Fill feedback info
activate FE
FE -> BE: Request POST feedback
deactivate FE
activate BE
BE -> BE: Save feedback
BE -->> Admin: Request Approve feedback
activate Admin
Admin -> BE: Approve feedback
deactivate Admin
BE -> BE: Update status of feedback
BE -->> FE: Return confirmation
BE -->> GF: Send feedback mail
hide footbox
@enduml